# <font color='blue'>Python para Ciência de Dados</font>
# <font color='blue'>Capítulo 14</font>


In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python usada neste Jupyter Notebook:', python_version())

Versão da Linguagem Python usada neste Jupyter Notebook: 3.10.12


# Introdução ao TensorFlow

In [2]:
# Instalando o tensorflow
#!pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.2/475.2 MB 2.1 MB/s eta 0:00:00m eta 0:00:010:00:02
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 39.1 MB/s eta 0:00:00
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 27.0 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.6/294.6 kB 33.7 MB/s eta 0:00:00
  Using cached wrapt-1.14.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 25.0 MB/s eta 0:00:00 MB/s eta 0:00:01:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.0/442.0 kB 21.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 27.7 MB/s eta 0:00:00m eta 0:00:010:01:01
     ━━━━━━━━━━━━━━━━━━━━━━


[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: /usr/bin/python3 -m pip install --upgrade pip


In [1]:
# Importando a biblioteca
import tensorflow as tf

2024-03-05 13:37:22.362246: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-05 13:37:22.362273: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-05 13:37:22.363109: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-05 13:37:22.368399: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-05 13:37:23.084131: W tensorflow/compiler/tf2

In [2]:
# Verificando a versão
tf.__version__

'2.15.0'

In [3]:
from tensorflow.keras import layers, models

# Carregar dados de treinamento e teste
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

# Pré-processamento dos dados
x_train, x_test = x_train / 255.0, x_test / 255.0

# Definir o modelo
model = models.Sequential([
 layers.Flatten(input_shape=(28, 28)),
 layers.Dense(128, activation='relu'),
 layers.Dropout(0.2),
 layers.Dense(10, activation='softmax')
])

# Compilar o modelo
model.compile(optimizer='adam',
 loss='sparse_categorical_crossentropy',
 metrics=['accuracy'])

# Treinar o modelo
model.fit(x_train, y_train, epochs=5)

# Avaliar o modelo
test_loss, test_acc = model.evaluate(x_test, y_test)
print('Test accuracy:', test_acc)

2024-03-04 17:48:51.559658: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-04 17:48:51.559685: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-04 17:48:51.560589: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-04 17:48:51.566551: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-04 17:48:52.296576: W tensorflow/compiler/tf2

11490434/11490434 [==============================] - 1s 0us/step


2024-03-04 17:48:57.380208: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


Epoch 1/5


2024-03-04 17:49:05.708156: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.


1875/1875 [==============================] - 3s 1ms/step - loss: 0.2948 - accuracy: 0.9142
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1406 - accuracy: 0.9585
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1061 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0852 - accuracy: 0.9738
Epoch 5/5
313/313 [==============================] - 0s 833us/step - loss: 0.0768 - accuracy: 0.9766
Test accuracy: 0.9765999913215637


## Explorando o TensorFlow

In [3]:
# Criando um tensor
hello = tf.constant('Hello, Python for DataScience!')

2024-03-05 13:37:35.599830: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


In [4]:
print(hello)

tf.Tensor(b'Hello, Python for DataScience!', shape=(), dtype=string)


## Operações

### Criação de Tensores

In [12]:
# Criar um tensor constante
tensor_const = tf.constant([[1, 2], [3, 4]])

print(tensor_const)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [11]:
# Criar um tensor variável
tensor_var = tf.Variable([5, 6, 7])

print(tensor_var)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([5, 6, 7], dtype=int32)>


In [9]:
# Criar um tensor preenchido com zeros
tensor_zeros = tf.zeros((3, 3))

print(tensor_zeros)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [10]:
# Criar um tensor preenchido com uns
tensor_ones = tf.ones((2, 2))

print(tensor_ones)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [14]:
# Criar um tensor com valores aleatórios de uma distribuição normal
tensor_random_normal = tf.random.normal((3, 3))

print(tensor_random_normal)

tf.Tensor(
[[ 0.6687336  -2.3767953  -0.5301165 ]
 [ 0.27705908 -0.9660335  -0.664342  ]
 [ 0.06038933  0.730116    0.49838436]], shape=(3, 3), dtype=float32)


### Operações Matemáticas

#### Adição de tensores

In [21]:
# Adição de tensores

# criando constantes
const_a = tf.constant(5)
const_b = tf.constant(9)

print(const_a)
print(const_b)

# Soma
total = const_a + const_b

print(total)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)


In [22]:
# Criando nodes no grafo computacional
node1 = tf.constant(5, dtype = tf.int32)
node2 = tf.constant(9, dtype = tf.int32)
node3 = tf.add(node1, node2)
 
# Executa o grafo
print("\nA soma do node1 com o node2 é:", node3)


A soma do node1 com o node2 é: tf.Tensor(14, shape=(), dtype=int32)


#### Subtração de tensores

In [42]:
# Tensores
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 0], [7, 9]])

In [43]:
print(tensor_a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [44]:
print(tensor_b)

tf.Tensor(
[[5 0]
 [7 9]], shape=(2, 2), dtype=int32)


In [45]:
# Subtração
diff = tf.subtract(tensor_a, tensor_b)

In [46]:
type(diff)

tensorflow.python.framework.ops.EagerTensor

In [47]:
print('\nSubtração entre os 2 tensores é: ', diff)


Subtração entre os 2 tensores é:  tf.Tensor(
[[-4  2]
 [-4 -5]], shape=(2, 2), dtype=int32)


#### Divisão

In [49]:
# Tensores
node1 = tf.constant(21, dtype = tf.int32)
node2 = tf.constant(7, dtype = tf.int32)

In [50]:
# Divisão
div = tf.math.truediv(node1, node2)

In [51]:
print('\nDivisão Entre os Tensores: \n', div)


Divisão Entre os Tensores: 
 tf.Tensor(3.0, shape=(), dtype=float64)


#### Multiplicação

In [57]:
# Criando tensores
tensor_a = tf.constant([[5., 3.]])
tensor_b = tf.constant([[4.],[8.]])

In [58]:
print(tensor_a)

tf.Tensor([[5. 3.]], shape=(1, 2), dtype=float32)


In [59]:
print(tensor_b)

tf.Tensor(
[[4.]
 [8.]], shape=(2, 1), dtype=float32)


In [60]:
# Multiplicação
# tf.math.multiply(X, Y) executa multiplicação element-wise 
# https://www.tensorflow.org/api_docs/python/tf/math/multiply
prod = tf.math.multiply(tensor_a, tensor_b)

In [61]:
print('\nProduto Element-wise Entre os Tensores: \n', prod)


Produto Element-wise Entre os Tensores: 
 tf.Tensor(
[[20. 12.]
 [40. 24.]], shape=(2, 2), dtype=float32)


#### Exponencial

In [67]:
# Criando tensores
tensor_a = tf.constant([[5., 3.]])
tensor_b = tf.constant([[4.],[8.]])

In [68]:
tensor_exp_a = tf.exp(tensor_a)

print(tensor_exp_a)

tf.Tensor([[148.41316   20.085537]], shape=(1, 2), dtype=float32)


In [69]:
tensor_exp_b = tf.exp(tensor_b)

print(tensor_exp_b)

tf.Tensor(
[[  54.59815]
 [2980.958  ]], shape=(2, 1), dtype=float32)


### Redução de Tensores

In [72]:
# Criando tensores
tensor_c = tf.constant([[9., 1.]])

# Redução de soma
tensor_sum = tf.reduce_sum(tensor_)

print(tensor_sum)

tf.Tensor(10.0, shape=(), dtype=float32)


In [74]:
# Redução de média
tensor_mean = tf.reduce_mean(tensor_c)

print(tensor_mean)

tf.Tensor(5.0, shape=(), dtype=float32)


### Álgebra Linear

In [76]:
# Produto interno
tensor_dot = tf.tensordot(tensor_a, tensor_b, axes=1)

print(tensor_dot)

tf.Tensor([[44.]], shape=(1, 1), dtype=float32)


In [77]:
# Transposição de tensor

# Matriz 1x2 virou 2x1
tensor_transpose = tf.transpose(tensor_a)

print(tensor_transpose)

tf.Tensor(
[[5.]
 [3.]], shape=(2, 1), dtype=float32)


In [78]:
# Transposição de tensor

# Matriz 2x1 virou 1x2
tensor_transpose = tf.transpose(tensor_b)

print(tensor_transpose)

tf.Tensor([[4. 8.]], shape=(1, 2), dtype=float32)


## tf.constant()

In [1]:
import tensorflow as tf

# Criar um tensor constante a partir de um escalar
tensor1 = tf.constant(5.0)

# Criar um tensor constante a partir de uma lista
tensor2 = tf.constant([1, 2, 3, 4, 5])

# Criar um tensor constante a partir de uma matriz NumPy
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
tensor3 = tf.constant(array)

# Especificar o tipo de dado e o nome do tensor
tensor4 = tf.constant(3.14, dtype=tf.float32, name='pi')

# Especificar a forma do tensor
tensor5 = tf.constant(0, shape=(2, 3))


2024-03-05 14:39:37.026867: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-05 14:39:37.026896: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-05 14:39:37.027727: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-05 14:39:37.033089: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-05 14:39:37.778902: W tensorflow/compiler/tf2

## tf.variable()

In [2]:
import tensorflow as tf

# Criar um tensor variável a partir de um escalar
variable1 = tf.Variable(5.0)

# Criar um tensor variável a partir de uma lista
variable2 = tf.Variable([1, 2, 3, 4, 5])

# Criar um tensor variável a partir de uma matriz NumPy
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
variable3 = tf.Variable(array)

# Especificar o tipo de dado e o nome do tensor
variable4 = tf.Variable(3.14, dtype=tf.float32, name='pi')

# Especificar que o tensor não é treinável
variable5 = tf.Variable(0, trainable=False)

## tf.zeros()

In [3]:
import tensorflow as tf

# Criar um tensor preenchido com zeros de forma (3, 3)
tensor1 = tf.zeros((3, 3))

# Criar um tensor preenchido com zeros de forma (2, 2, 2) e tipo de dado tf.int32
tensor2 = tf.zeros((2, 2, 2), dtype=tf.int32)

# Criar um tensor preenchido com zeros de forma (4,) e nome 'zeros_tensor'
tensor3 = tf.zeros([4], name='zeros_tensor')

## tf.ones()

In [5]:
import tensorflow as tf

# Criar um tensor preenchido com uns
ones_tensor = tf.ones(shape=(2, 2))
# Especificar o nome do tensor
ones_named_tensor = tf.ones(shape=(2, 2), name='ones_tensor')

## tf.fill()

In [6]:
import tensorflow as tf

# Criar um tensor preenchido com o valor 7
filled_tensor = tf.fill(dims=(2, 3), value=7)

print(filled_tensor)

tf.Tensor(
[[7 7 7]
 [7 7 7]], shape=(2, 3), dtype=int32)


### tf.random.normal()

In [8]:
import tensorflow as tf

# Criar um tensor com forma (3, 3) contendo valores amostrados de uma distribuição normal
tensor = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0)

print(tensor)

tf.Tensor(
[[ 0.763717    1.6245904   0.8401559 ]
 [ 0.02932856 -0.08718653  0.22539632]
 [ 0.7837219  -0.62873846 -1.4869293 ]], shape=(3, 3), dtype=float32)


### tf.random.uniform()

In [10]:
import tensorflow as tf

# Criar um tensor com forma (3, 3) contendo valores amostrados de uma distribuição uniforme no intervalo [0, 1]
tensor = tf.random.uniform(shape=(3, 3))

print(tensor)

tf.Tensor(
[[0.12028646 0.03995156 0.02232838]
 [0.00733566 0.5506784  0.58341694]
 [0.09539127 0.9294827  0.04922581]], shape=(3, 3), dtype=float32)


### tf.add()

In [11]:
import tensorflow as tf

# Criar dois tensores
tensor1 = tf.constant([1, 2, 3])
tensor2 = tf.constant([4, 5, 6])

# Realizar a adição dos tensores
result = tf.add(tensor1, tensor2)

print(result.numpy())  # Convertendo para NumPy array para visualização

[5 7 9]


### tf.subtract()

In [12]:
import tensorflow as tf

# Criar dois tensores
tensor1 = tf.constant([1, 2, 3])
tensor2 = tf.constant([4, 5, 6])

# Realizar a subtração dos tensores
result = tf.subtract(tensor1, tensor2)

print(result.numpy())  # Convertendo para NumPy array para visualização

[-3 -3 -3]


### tf.multiply()

In [13]:
import tensorflow as tf

# Criar dois tensores
tensor1 = tf.constant([1, 2, 3])
tensor2 = tf.constant([4, 5, 6])

# Realizar a multiplicação dos tensores
result = tf.multiply(tensor1, tensor2)

print(result.numpy())  # Convertendo para NumPy array para visualização

[ 4 10 18]


### tf.divide()

In [14]:
import tensorflow as tf

# Criar dois tensores
tensor1 = tf.constant([4, 6, 8])
tensor2 = tf.constant([2, 3, 2])

# Realizar a divisão dos tensores
result = tf.divide(tensor1, tensor2)

print(result.numpy())  # Convertendo para NumPy array para visualização

[2. 2. 4.]


### tf.exp()

In [15]:
import tensorflow as tf

# Criar um tensor
tensor = tf.constant([1.0, 2.0, 3.0])

# Calcular a exponencial do tensor
result = tf.exp(tensor)

print(result.numpy())  # Convertendo para NumPy array para visualização

[ 2.7182817  7.389056  20.085537 ]


### tf.log()

In [17]:
import tensorflow as tf

# Criar um tensor
tensor = tf.constant([1.0, 2.0, 3.0])

# Calcular o logaritmo natural do tensor
result = tf.math.log(tensor)

print(result.numpy())  # Convertendo para NumPy array para visualização

[0.        0.6931472 1.0986123]


### tf.sqrt()

In [18]:
import tensorflow as tf

# Criar um tensor
tensor = tf.constant([4.0, 9.0, 16.0])

# Calcular a raiz quadrada do tensor
result = tf.sqrt(tensor)

print(result.numpy())  # Convertendo para NumPy array para visualização

[2. 3. 4.]


### tf.sin()

In [19]:
import tensorflow as tf
import numpy as np

# Criar um tensor
tensor = tf.constant([0.0, np.pi/2, np.pi])

# Calcular o seno do tensor
result = tf.sin(tensor)

print(result.numpy())  # Convertendo para NumPy array para visualização

[ 0.000000e+00  1.000000e+00 -8.742278e-08]


### tf.cos()

In [20]:
import tensorflow as tf
import numpy as np

# Criar um tensor
tensor = tf.constant([0.0, np.pi/2, np.pi])

# Calcular o cosseno do tensor
result = tf.cos(tensor)

print(result.numpy())  # Convertendo para NumPy array para visualização

[ 1.000000e+00 -4.371139e-08 -1.000000e+00]


### tf.reduce_sum()

In [21]:
import tensorflow as tf

# Criar um tensor
tensor = tf.constant([[1, 2], [3, 4]])

# Calcular a soma do tensor
result = tf.reduce_sum(tensor)

print(result.numpy())  # Convertendo para NumPy array para visualização

10


### tf.reduce_mean()

In [23]:
import tensorflow as tf

# Criar um tensor
tensor = tf.constant([[1, 2], [3, 4]])

# Calcular a média do tensor
result = tf.reduce_mean(tensor)

print(result.numpy())  # Convertendo para NumPy array para visualização

2


### tf.reduce_max()

In [24]:
import tensorflow as tf

# Criar um tensor
tensor = tf.constant([[1, 2], [3, 4]])

# Calcular o valor máximo do tensor
result = tf.reduce_max(tensor)

print(result.numpy())  # Convertendo para NumPy array para visualização



4


### tf.reduce_min()

In [25]:
import tensorflow as tf

# Criar um tensor
tensor = tf.constant([[1, 2], [3, 4]])

# Calcular o valor mínimo do tensor
result = tf.reduce_min(tensor)

print(result.numpy())  # Convertendo para NumPy array para visualização



1


### tf.linalg.det()

In [26]:
import tensorflow as tf

# Criar uma matriz
matrix = tf.constant([[1, 2], [3, 4]], dtype=tf.float64)

# Calcular o determinante da matriz
determinant = tf.linalg.det(matrix)

print(determinant.numpy())  # Convertendo para NumPy array para visualização

-2.0000000000000004


### tf.linalg.inv()

In [27]:
import tensorflow as tf

# Criar uma matriz
matrix = tf.constant([[1, 2], [3, 4]], dtype=tf.float64)

# Calcular a inversa da matriz
inverse = tf.linalg.inv(matrix)

print(inverse.numpy())  # Convertendo para NumPy array para visualização


[[-2.   1. ]
 [ 1.5 -0.5]]


### tf.matmul()

In [30]:
import tensorflow as tf

# Criar dois tensores
a = tf.constant([[1, 3], [5, 7]])
b = tf.constant([[2, 4], [6, 8]])

# Multiplicar os tensores
result = tf.matmul(a, b)

print(result.numpy())  # Convertendo para NumPy array para visualização


[[20 28]
 [52 76]]


### tf.linalg.norm()

In [33]:
import tensorflow as tf

# Criar um tensor
tensor = tf.constant([1., 2., 3., 4.])

# Calcular a norma do tensor
norm = tf.linalg.norm(tensor, ord='euclidean')

print(norm.numpy())  # Convertendo para NumPy array para visualização



5.477226


### tf.transpose()

In [34]:
import tensorflow as tf

# Criar um tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

# Transpor o tensor
transposed_tensor = tf.transpose(tensor)

print(transposed_tensor.numpy())  # Convertendo para NumPy array para visualização


[[1 4]
 [2 5]
 [3 6]]


### tf.linalg.eig()

In [35]:
import tensorflow as tf

# Criar uma matriz
matrix = tf.constant([[1.0, 2.0], [3.0, 4.0]])

# Calcular os autovalores e autovetores
eigenvalues, eigenvectors = tf.linalg.eig(matrix)

print("Autovalores:")
print(eigenvalues.numpy())

print("\nAutovetores:")
print(eigenvectors.numpy())


Autovalores:
[-0.37228122+0.j  5.372281  +0.j]

Autovetores:
[[-0.8245648 +0.j -0.41597357+0.j]
 [ 0.56576747+0.j -0.90937674+0.j]]


### tf.keras.layers.Dense() 

In [36]:
import tensorflow as tf

# Criar uma camada densa com 64 neurônios e ativação ReLU
dense_layer = tf.keras.layers.Dense(units=64, activation='relu')

# Usar a camada em um modelo
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(784,)),  # Entrada da camada
    dense_layer  # Camada densa
])

# Visualizar o resumo do modelo
model.summary()



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                50240     
                                                                 
Total params: 50240 (196.25 KB)
Trainable params: 50240 (196.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


### tf.keras.layers.Conv2D()

In [37]:

import tensorflow as tf

# Criar uma camada de convolução com 32 filtros, tamanho de kernel 3x3, ativação ReLU e preenchimento 'same'
conv_layer = tf.keras.layers.Conv2D(filters=32, kernel_size=(3, 3), activation='relu', padding='same')

# Usar a camada em um modelo
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(28, 28, 1)),  # Entrada da camada
    conv_layer  # Camada de convolução
])

# Visualizar o resumo do modelo
model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 28, 28, 32)        320       
                                                                 
Total params: 320 (1.25 KB)
Trainable params: 320 (1.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


### tf.keras.layers.LSTM()

In [38]:
import tensorflow as tf

# Criar uma camada LSTM com 64 unidades
lstm_layer = tf.keras.layers.LSTM(units=64)

# Usar a camada em um modelo
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(10, 32)),  # Entrada da camada (sequência de 10 vetores de tamanho 32)
    lstm_layer  # Camada LSTM
])

# Visualizar o resumo do modelo
model.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 64)                24832     
                                                                 
Total params: 24832 (97.00 KB)
Trainable params: 24832 (97.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


### tf.keras.activations.relu()

In [39]:
import tensorflow as tf

# Criar um tensor de exemplo
x = tf.constant([-1.0, 2.0, -3.0, 4.0])

# Aplicar a função ReLU ao tensor
output = tf.keras.activations.relu(x)

print(output.numpy())  # Convertendo para NumPy array para visualização


[0. 2. 0. 4.]


### tf.keras.activations.sigmoid()

In [40]:
import tensorflow as tf

# Criar um tensor de exemplo
x = tf.constant([-1.0, 0.0, 1.0])

# Aplicar a função sigmoid ao tensor
output = tf.keras.activations.sigmoid(x)

print(output.numpy())  # Convertendo para NumPy array para visualização


[0.26894143 0.5        0.7310586 ]


### tf.keras.activations.softmax()

In [41]:
import tensorflow as tf

# Criar um tensor de exemplo
x = tf.constant([[1.0, 2.0, 3.0]])

# Aplicar a função Softmax ao tensor
output = tf.keras.activations.softmax(x)

print(output.numpy())  # Convertendo para NumPy array para visualização


[[0.09003057 0.24472848 0.66524094]]


### tf.keras.initializers.RandomNormal()

In [42]:
import tensorflow as tf

# Criar um inicializador com distribuição normal
initializer = tf.keras.initializers.RandomNormal(mean=0.0, stddev=0.1)

# Inicializar uma camada com pesos gerados aleatoriamente
layer = tf.keras.layers.Dense(units=64, kernel_initializer=initializer)

# Usar a camada em um modelo
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(784,)),  # Entrada da camada
    layer  # Camada com pesos inicializados aleatoriamente
])

# Visualizar o resumo do modelo
model.summary()


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 64)                50240     
                                                                 
Total params: 50240 (196.25 KB)
Trainable params: 50240 (196.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


### tf.keras.initializers.GlorotUniform()

In [44]:
import tensorflow as tf

# Criar um inicializador com inicialização de Glorot
initializer = tf.keras.initializers.GlorotUniform()

# Inicializar uma camada com pesos gerados aleatoriamente
layer = tf.keras.layers.Dense(units=64, kernel_initializer=initializer)

# Usar a camada em um modelo
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(784,)),  # Entrada da camada
    layer  # Camada com pesos inicializados aleatoriamente
])

# Visualizar o resumo do modelo
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 64)                50240     
                                                                 
Total params: 50240 (196.25 KB)
Trainable params: 50240 (196.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


### tf.keras.losses.BinaryCrossentropy()

In [45]:
import tensorflow as tf

# Definir rótulos verdadeiros e previsões
true_labels = tf.constant([1, 0, 1, 0])
predictions = tf.constant([0.9, 0.2, 0.8, 0.1])

# Calcular a perda usando a entropia cruzada binária
loss_function = tf.keras.losses.BinaryCrossentropy()
loss = loss_function(true_labels, predictions)

print(loss.numpy())  # Imprimir a perda calculada

0.1642519


### tf.keras.losses.CategoricalCrossentropy()

In [46]:
import tensorflow as tf

# Definir rótulos verdadeiros e previsões
true_labels = tf.constant([[0, 1, 0], [1, 0, 0], [0, 0, 1]])  # One-hot encoded labels
predictions = tf.constant([[0.1, 0.8, 0.1], [0.9, 0.1, 0.0], [0.0, 0.1, 0.9]])

# Calcular a perda usando a entropia cruzada categórica
loss_function = tf.keras.losses.CategoricalCrossentropy()
loss = loss_function(true_labels, predictions)

print(loss.numpy())  # Imprimir a perda calculada


0.14462154


### tf.keras.optimizers.Adam()

In [50]:
import tensorflow as tf
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Carregar o conjunto de dados Iris
iris = load_iris()
X = iris.data
y = iris.target

# Dividir os dados em conjunto de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Criar um otimizador Adam com a taxa de aprendizado padrão
optimizer = tf.keras.optimizers.Adam()

# Usar o otimizador em um modelo
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Treinar o modelo
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X, y))


Epoch 1/10
4/4 [==============================] - 0s 46ms/step - loss: 3.2554 - accuracy: 0.0000e+00 - val_loss: 2.9996 - val_accuracy: 0.0000e+00
Epoch 2/10
4/4 [==============================] - 0s 9ms/step - loss: 2.8559 - accuracy: 0.0417 - val_loss: 2.6203 - val_accuracy: 0.3267
Epoch 3/10
4/4 [==============================] - 0s 8ms/step - loss: 2.4884 - accuracy: 0.3250 - val_loss: 2.2802 - val_accuracy: 0.3333
Epoch 4/10
4/4 [==============================] - 0s 9ms/step - loss: 2.1695 - accuracy: 0.3333 - val_loss: 1.9783 - val_accuracy: 0.3333
Epoch 5/10
4/4 [==============================] - 0s 9ms/step - loss: 1.8816 - accuracy: 0.3333 - val_loss: 1.7192 - val_accuracy: 0.3333
Epoch 6/10
4/4 [==============================] - 0s 9ms/step - loss: 1.6399 - accuracy: 0.3667 - val_loss: 1.5070 - val_accuracy: 0.4333
Epoch 7/10
4/4 [==============================] - 0s 9ms/step - loss: 1.4429 - accuracy: 0.4583 - val_loss: 1.3417 - val_accuracy: 0.5200
Epoch 8/10
4/4 [=========

### tf.keras.optimizers.SGD()

In [51]:
import tensorflow as tf

# Definir um modelo
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(784,)),
    tf.keras.layers.Dense(10, activation='softmax')
])

# Compilar o modelo com o otimizador SGD
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.9)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

### tf.keras.metrics.Accuracy()

In [106]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

import sqlite3

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler

import tensorflow as tf


In [107]:
# fixando seed para reprodutibilidade
seed = 42
np.random.seed(seed)

In [108]:
connection = sqlite3.connect('databases/iris.sqlite')
data = pd.read_sql_query(''' SELECT * FROM IRIS ''', connection)
print("Shape of data: {}".format(data.shape))

Shape of data: (150, 6)


In [109]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [110]:
Y = data['Species']
X = data.drop(['Id', 'Species'], axis=1)
print("Shape das features de Entrada: {}".format(X.shape))
print("Shape das features de Saida: {}".format(Y.shape))

Shape das features de Entrada: (150, 4)
Shape das features de Saida: (150,)


In [111]:
Y.value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [112]:
x_train, x_test, y_train, y_test = train_test_split(X, Y_final, test_size=0.2, random_state=seed, stratify=Y_encoded, shuffle=True)

print("Training Input shape\t: {}".format(x_train.shape))
print("Testing Input shape\t: {}".format(x_test.shape))
print("Training Output shape\t: {}".format(y_train.shape))
print("Testing Output shape\t: {}".format(y_test.shape))

Training Input shape	: (120, 4)
Testing Input shape	: (30, 4)
Training Output shape	: (120, 3)
Testing Output shape	: (30, 3)


In [113]:
lbl_clf = LabelEncoder()
Y_encoded = lbl_clf.fit_transform(Y)

# Keras exige que seu recurso de saída tenha valores codificados one-hot.
Y_final = tf.keras.utils.to_categorical(Y_encoded)

print("Portanto, nosso formato final do recurso de saída será {}".format(Y_final.shape))

Portanto, nosso formato final do recurso de saída será (150, 3)


In [114]:
std_clf = StandardScaler()
x_train_new = std_clf.fit_transform(x_train)
x_test_new = std_clf.transform(x_test)

In [115]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(10, input_dim=4, activation=tf.nn.relu, kernel_initializer='he_normal', 
                                kernel_regularizer=tf.keras.regularizers.l2(0.01)))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Dropout(0.3))
model.add(tf.keras.layers.Dense(7, activation=tf.nn.relu, kernel_initializer='he_normal', 
                                kernel_regularizer=tf.keras.regularizers.l1_l2(l1=0.001, l2=0.001)))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Dropout(0.3))
model.add(tf.keras.layers.Dense(5, activation=tf.nn.relu, kernel_initializer='he_normal', 
                                kernel_regularizer=tf.keras.regularizers.l1_l2(l1=0.001, l2=0.001)))
model.add(tf.keras.layers.Dense(3, activation=tf.nn.softmax))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

iris_model = model.fit(x_train_new, y_train, epochs=50, batch_size=7)

Epoch 1/50
18/18 [==============================] - 1s 1ms/step - loss: 1.7146 - accuracy: 0.2667
Epoch 2/50
18/18 [==============================] - 0s 1ms/step - loss: 1.7001 - accuracy: 0.3417
Epoch 3/50
18/18 [==============================] - 0s 1ms/step - loss: 1.7920 - accuracy: 0.2833
Epoch 4/50
18/18 [==============================] - 0s 1ms/step - loss: 1.6710 - accuracy: 0.3333
Epoch 5/50
18/18 [==============================] - 0s 2ms/step - loss: 1.5442 - accuracy: 0.3083
Epoch 6/50
18/18 [==============================] - 0s 1ms/step - loss: 1.5777 - accuracy: 0.3083
Epoch 7/50
18/18 [==============================] - 0s 1ms/step - loss: 1.6671 - accuracy: 0.2000
Epoch 8/50
18/18 [==============================] - 0s 1ms/step - loss: 1.5423 - accuracy: 0.2917
Epoch 9/50
18/18 [==============================] - 0s 1ms/step - loss: 1.4942 - accuracy: 0.3000
Epoch 10/50
18/18 [==============================] - 0s 1ms/step - loss: 1.4408 - accuracy: 0.3500
Epoch 11/50
18/18 [

In [116]:
model.evaluate(x_test_new, y_test)

1/1 [==============================] - 0s 124ms/step - loss: 0.6236 - accuracy: 0.8000


[0.6236487627029419, 0.800000011920929]

### tf.keras.metrics.Precision()

In [95]:
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification

# Gerar dados de exemplo
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=42)

# Dividir os dados em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalizar os dados
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Criar um modelo de classificação binária simples
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Compilar o modelo com a métrica de precisão
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=[tf.keras.metrics.Precision()])

# Treinar o modelo
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.1)

# Avaliar o modelo no conjunto de teste
test_loss, test_precision = model.evaluate(X_test, y_test)
print(f'Test Precision: {test_precision}')


Epoch 1/10
23/23 [==============================] - 1s 7ms/step - loss: 0.6835 - precision_3: 0.6069 - val_loss: 0.5780 - val_precision_3: 0.8077
Epoch 2/10
23/23 [==============================] - 0s 2ms/step - loss: 0.5691 - precision_3: 0.8250 - val_loss: 0.4948 - val_precision_3: 0.9630
Epoch 3/10
23/23 [==============================] - 0s 2ms/step - loss: 0.4960 - precision_3: 0.8602 - val_loss: 0.4383 - val_precision_3: 0.9032
Epoch 4/10
23/23 [==============================] - 0s 2ms/step - loss: 0.4423 - precision_3: 0.8727 - val_loss: 0.3971 - val_precision_3: 0.9062
Epoch 5/10
23/23 [==============================] - 0s 2ms/step - loss: 0.4046 - precision_3: 0.8791 - val_loss: 0.3684 - val_precision_3: 0.9062
Epoch 6/10
23/23 [==============================] - 0s 2ms/step - loss: 0.3759 - precision_3: 0.8879 - val_loss: 0.3450 - val_precision_3: 0.9355
Epoch 7/10
23/23 [==============================] - 0s 2ms/step - loss: 0.3546 - precision_3: 0.8899 - val_loss: 0.3272 - va

### tf.keras.metrics.Recall()

In [121]:
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification

# Gerar dados de exemplo
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=42)

# Dividir os dados em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalizar os dados
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Criar um modelo de classificação binária simples
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Compilar o modelo com a métrica de precisão
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=[tf.keras.metrics.Recall()])

# Treinar o modelo
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.1)

# Avaliar o modelo no conjunto de teste
test_loss, test_precision = model.evaluate(X_test, y_test)
print(f'Test Precision: {test_precision}')

Epoch 1/10
23/23 [==============================] - 1s 7ms/step - loss: 0.6424 - recall_3: 0.9160 - val_loss: 0.5872 - val_recall_3: 0.9167
Epoch 2/10
23/23 [==============================] - 0s 2ms/step - loss: 0.5324 - recall_3: 0.8235 - val_loss: 0.4848 - val_recall_3: 0.8333
Epoch 3/10
23/23 [==============================] - 0s 2ms/step - loss: 0.4652 - recall_3: 0.7955 - val_loss: 0.4282 - val_recall_3: 0.8333
Epoch 4/10
23/23 [==============================] - 0s 2ms/step - loss: 0.4226 - recall_3: 0.8011 - val_loss: 0.3890 - val_recall_3: 0.8333
Epoch 5/10
23/23 [==============================] - 0s 2ms/step - loss: 0.3890 - recall_3: 0.8179 - val_loss: 0.3598 - val_recall_3: 0.8611
Epoch 6/10
23/23 [==============================] - 0s 2ms/step - loss: 0.3653 - recall_3: 0.8291 - val_loss: 0.3350 - val_recall_3: 0.8611
Epoch 7/10
23/23 [==============================] - 0s 2ms/step - loss: 0.3470 - recall_3: 0.8403 - val_loss: 0.3212 - val_recall_3: 0.8333
Epoch 8/10
23/23 [==

### Métricas

In [126]:
conf_matrix = [[90, 10],
               [5, 95]]

TN, FP = conf_matrix[0]
FN, TP = conf_matrix[1]

precision = TP / (TP + FP)
recall = TP / (TP + FN)
accuracy = (TP + TN) / (TP + FP + FN + TN)

print("Precision:", precision)
print("Recall:", recall)
print("Accuracy:", accuracy)


Precision: 0.9047619047619048
Recall: 0.95
Accuracy: 0.925


### tf.keras.callbacks.Callback()

In [129]:
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification

# Gerar dados de exemplo
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=42)

# Dividir os dados em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalizar os dados
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Criar um modelo de classificação binária simples
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Compilar o modelo
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Criar o callback ModelCheckpoint para salvar o modelo
checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(filepath='model_checkpoint.h5', 
                                                         monitor='val_accuracy', 
                                                         save_best_only=True,
                                                         verbose=1)

# Treinar o modelo com o callback ModelCheckpoint
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X, y), callbacks=[checkpoint_callback])


Epoch 1/10


/home/igor/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py:1260: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(32, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return dispatch_target(*args, **kwargs)


 1/25 [>.............................] - ETA: 6s - loss: 0.0000e+00 - accuracy: 0.5000
Epoch 1: val_accuracy improved from -inf to 0.55100, saving model to model_checkpoint.h5
25/25 [==============================] - 1s 20ms/step - loss: 0.0000e+00 - accuracy: 0.5537 - val_loss: 0.0000e+00 - val_accuracy: 0.5510
Epoch 2/10
 1/25 [>.............................] - ETA: 0s - loss: 0.0000e+00 - accuracy: 0.5000
Epoch 2: val_accuracy did not improve from 0.55100
25/25 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.5412 - val_loss: 0.0000e+00 - val_accuracy: 0.5270
Epoch 3/10
 1/25 [>.............................] - ETA: 0s - loss: 0.0000e+00 - accuracy: 0.4062

/home/igor/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py:1260: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(None, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return dispatch_target(*args, **kwargs)
/home/igor/.local/lib/python3.10/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(



Epoch 3: val_accuracy did not improve from 0.55100
25/25 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.5288 - val_loss: 0.0000e+00 - val_accuracy: 0.5080
Epoch 4/10
 1/25 [>.............................] - ETA: 0s - loss: 0.0000e+00 - accuracy: 0.7188
Epoch 4: val_accuracy did not improve from 0.55100
25/25 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.5150 - val_loss: 0.0000e+00 - val_accuracy: 0.5030
Epoch 5/10
 1/25 [>.............................] - ETA: 0s - loss: 0.0000e+00 - accuracy: 0.4375
Epoch 5: val_accuracy did not improve from 0.55100
25/25 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.5138 - val_loss: 0.0000e+00 - val_accuracy: 0.5000
Epoch 6/10
 1/25 [>.............................] - ETA: 0s - loss: 0.0000e+00 - accuracy: 0.6250
Epoch 6: val_accuracy did not improve from 0.55100
25/25 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.5100

### tf.keras.callbacks.EarlyStopping()

In [131]:
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification

# Gerar dados de exemplo
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=42)

# Dividir os dados em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalizar os dados
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Criar um modelo de classificação binária simples
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Compilar o modelo
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Criar o callback EarlyStopping para interromper o treinamento se a precisão de validação não melhorar por 5 épocas
early_stopping_callback = tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=5, verbose=1)

# Treinar o modelo com o callback EarlyStopping
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X, y), callbacks=[early_stopping_callback])


Epoch 1/100


/home/igor/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py:1260: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(32, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return dispatch_target(*args, **kwargs)


25/25 [==============================] - 1s 7ms/step - loss: 0.0000e+00 - accuracy: 0.5250 - val_loss: 0.0000e+00 - val_accuracy: 0.5120
Epoch 2/100
25/25 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.5163 - val_loss: 0.0000e+00 - val_accuracy: 0.5040
Epoch 3/100
 1/25 [>.............................] - ETA: 0s - loss: 0.0000e+00 - accuracy: 0.6562

/home/igor/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py:1260: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(None, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return dispatch_target(*args, **kwargs)


25/25 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.5138 - val_loss: 0.0000e+00 - val_accuracy: 0.5020
Epoch 4/100
25/25 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.5125 - val_loss: 0.0000e+00 - val_accuracy: 0.5010
Epoch 5/100
25/25 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.5100 - val_loss: 0.0000e+00 - val_accuracy: 0.5010
Epoch 6/100
25/25 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.5100 - val_loss: 0.0000e+00 - val_accuracy: 0.5000
Epoch 6: early stopping


### tf.keras.utils.to_categorical()

In [132]:
import numpy as np
import tensorflow as tf

# Rótulos de classe (inteiros)
y = np.array([0, 1, 2, 1, 0])

# Converter para representação one-hot
y_one_hot = tf.keras.utils.to_categorical(y)

print(y_one_hot)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [157]:
# One-hot encoding com scikit-learn
from sklearn.preprocessing import OneHotEncoder

categories = ["maçã", "banana", "laranja"]
labels = np.array(categories).reshape(-1, 1)

# Inicializar o codificador
encoder = OneHotEncoder()

# Ajustar e transformar os dados
one_hot_encoded = encoder.fit_transform(labels)

# Converter para array NumPy
one_hot_encoded_array = one_hot_encoded.toarray()

print(one_hot_encoded_array)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [136]:
import numpy as np
import tensorflow as tf

categories = ["maçã", "banana", "laranja"]
encoded = tf.keras.utils.to_categorical(np.arange(len(categories)))

print(encoded)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Fim