# <font color='blue'>Python para Ciência de Dados</font>
# <font color='blue'>Capítulo 14</font>


In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python usada neste Jupyter Notebook:', python_version())

Versão da Linguagem Python usada neste Jupyter Notebook: 3.10.12


# Introdução ao TensorFlow

In [2]:
# Instalando o tensorflow
#!pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.2/475.2 MB 2.1 MB/s eta 0:00:00m eta 0:00:010:00:02
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 39.1 MB/s eta 0:00:00
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 27.0 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.6/294.6 kB 33.7 MB/s eta 0:00:00
  Using cached wrapt-1.14.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 25.0 MB/s eta 0:00:00 MB/s eta 0:00:01:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.0/442.0 kB 21.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 27.7 MB/s eta 0:00:00m eta 0:00:010:01:01
     ━━━━━━━━━━━━━━━━━━━━━━


[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: /usr/bin/python3 -m pip install --upgrade pip


In [1]:
# Importando a biblioteca
import tensorflow as tf

2024-03-05 13:37:22.362246: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-05 13:37:22.362273: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-05 13:37:22.363109: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-05 13:37:22.368399: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-05 13:37:23.084131: W tensorflow/compiler/tf2

In [2]:
# Verificando a versão
tf.__version__

'2.15.0'

In [3]:
from tensorflow.keras import layers, models

# Carregar dados de treinamento e teste
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

# Pré-processamento dos dados
x_train, x_test = x_train / 255.0, x_test / 255.0

# Definir o modelo
model = models.Sequential([
 layers.Flatten(input_shape=(28, 28)),
 layers.Dense(128, activation='relu'),
 layers.Dropout(0.2),
 layers.Dense(10, activation='softmax')
])

# Compilar o modelo
model.compile(optimizer='adam',
 loss='sparse_categorical_crossentropy',
 metrics=['accuracy'])

# Treinar o modelo
model.fit(x_train, y_train, epochs=5)

# Avaliar o modelo
test_loss, test_acc = model.evaluate(x_test, y_test)
print('Test accuracy:', test_acc)

2024-03-04 17:48:51.559658: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-04 17:48:51.559685: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-04 17:48:51.560589: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-04 17:48:51.566551: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-04 17:48:52.296576: W tensorflow/compiler/tf2

11490434/11490434 [==============================] - 1s 0us/step


2024-03-04 17:48:57.380208: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


Epoch 1/5


2024-03-04 17:49:05.708156: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.


1875/1875 [==============================] - 3s 1ms/step - loss: 0.2948 - accuracy: 0.9142
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1406 - accuracy: 0.9585
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1061 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0852 - accuracy: 0.9738
Epoch 5/5
313/313 [==============================] - 0s 833us/step - loss: 0.0768 - accuracy: 0.9766
Test accuracy: 0.9765999913215637


## Explorando o TensorFlow

In [3]:
# Criando um tensor
hello = tf.constant('Hello, Python for DataScience!')

2024-03-05 13:37:35.599830: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


In [4]:
print(hello)

tf.Tensor(b'Hello, Python for DataScience!', shape=(), dtype=string)


## Operações

### Criação de Tensores

In [12]:
# Criar um tensor constante
tensor_const = tf.constant([[1, 2], [3, 4]])

print(tensor_const)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [11]:
# Criar um tensor variável
tensor_var = tf.Variable([5, 6, 7])

print(tensor_var)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([5, 6, 7], dtype=int32)>


In [9]:
# Criar um tensor preenchido com zeros
tensor_zeros = tf.zeros((3, 3))

print(tensor_zeros)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [10]:
# Criar um tensor preenchido com uns
tensor_ones = tf.ones((2, 2))

print(tensor_ones)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [14]:
# Criar um tensor com valores aleatórios de uma distribuição normal
tensor_random_normal = tf.random.normal((3, 3))

print(tensor_random_normal)

tf.Tensor(
[[ 0.6687336  -2.3767953  -0.5301165 ]
 [ 0.27705908 -0.9660335  -0.664342  ]
 [ 0.06038933  0.730116    0.49838436]], shape=(3, 3), dtype=float32)


### Operações Matemáticas

#### Adição de tensores

In [21]:
# Adição de tensores

# criando constantes
const_a = tf.constant(5)
const_b = tf.constant(9)

print(const_a)
print(const_b)

# Soma
total = const_a + const_b

print(total)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)


In [22]:
# Criando nodes no grafo computacional
node1 = tf.constant(5, dtype = tf.int32)
node2 = tf.constant(9, dtype = tf.int32)
node3 = tf.add(node1, node2)
 
# Executa o grafo
print("\nA soma do node1 com o node2 é:", node3)


A soma do node1 com o node2 é: tf.Tensor(14, shape=(), dtype=int32)


#### Subtração de tensores

In [42]:
# Tensores
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 0], [7, 9]])

In [43]:
print(tensor_a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [44]:
print(tensor_b)

tf.Tensor(
[[5 0]
 [7 9]], shape=(2, 2), dtype=int32)


In [45]:
# Subtração
diff = tf.subtract(tensor_a, tensor_b)

In [46]:
type(diff)

tensorflow.python.framework.ops.EagerTensor

In [47]:
print('\nSubtração entre os 2 tensores é: ', diff)


Subtração entre os 2 tensores é:  tf.Tensor(
[[-4  2]
 [-4 -5]], shape=(2, 2), dtype=int32)


#### Divisão

In [49]:
# Tensores
node1 = tf.constant(21, dtype = tf.int32)
node2 = tf.constant(7, dtype = tf.int32)

In [50]:
# Divisão
div = tf.math.truediv(node1, node2)

In [51]:
print('\nDivisão Entre os Tensores: \n', div)


Divisão Entre os Tensores: 
 tf.Tensor(3.0, shape=(), dtype=float64)


#### Multiplicação

In [57]:
# Criando tensores
tensor_a = tf.constant([[5., 3.]])
tensor_b = tf.constant([[4.],[8.]])

In [58]:
print(tensor_a)

tf.Tensor([[5. 3.]], shape=(1, 2), dtype=float32)


In [59]:
print(tensor_b)

tf.Tensor(
[[4.]
 [8.]], shape=(2, 1), dtype=float32)


In [60]:
# Multiplicação
# tf.math.multiply(X, Y) executa multiplicação element-wise 
# https://www.tensorflow.org/api_docs/python/tf/math/multiply
prod = tf.math.multiply(tensor_a, tensor_b)

In [61]:
print('\nProduto Element-wise Entre os Tensores: \n', prod)


Produto Element-wise Entre os Tensores: 
 tf.Tensor(
[[20. 12.]
 [40. 24.]], shape=(2, 2), dtype=float32)


#### Exponencial

In [67]:
# Criando tensores
tensor_a = tf.constant([[5., 3.]])
tensor_b = tf.constant([[4.],[8.]])

In [68]:
tensor_exp_a = tf.exp(tensor_a)

print(tensor_exp_a)

tf.Tensor([[148.41316   20.085537]], shape=(1, 2), dtype=float32)


In [69]:
tensor_exp_b = tf.exp(tensor_b)

print(tensor_exp_b)

tf.Tensor(
[[  54.59815]
 [2980.958  ]], shape=(2, 1), dtype=float32)


### Redução de Tensores

In [72]:
# Criando tensores
tensor_c = tf.constant([[9., 1.]])

# Redução de soma
tensor_sum = tf.reduce_sum(tensor_)

print(tensor_sum)

tf.Tensor(10.0, shape=(), dtype=float32)


In [74]:
# Redução de média
tensor_mean = tf.reduce_mean(tensor_c)

print(tensor_mean)

tf.Tensor(5.0, shape=(), dtype=float32)


### Álgebra Linear

In [76]:
# Produto interno
tensor_dot = tf.tensordot(tensor_a, tensor_b, axes=1)

print(tensor_dot)

tf.Tensor([[44.]], shape=(1, 1), dtype=float32)


In [77]:
# Transposição de tensor

# Matriz 1x2 virou 2x1
tensor_transpose = tf.transpose(tensor_a)

print(tensor_transpose)

tf.Tensor(
[[5.]
 [3.]], shape=(2, 1), dtype=float32)


In [78]:
# Transposição de tensor

# Matriz 2x1 virou 1x2
tensor_transpose = tf.transpose(tensor_b)

print(tensor_transpose)

tf.Tensor([[4. 8.]], shape=(1, 2), dtype=float32)


## Fim